import keyMirror from 'key-mirror';

export default keyMirror({
	LOGIN_SUCCESS:null,
	LOGIN_FAILURE:null,

	GET_CAPTCHA_SUCCESS:null,
	GET_CAPTCHA_FAILURE:null,

	GET_ANSWER_SUCCESS:null,
	GET_ANSWER_FAILURE:null,

	FEEDBACK_SUCCESS:null,
	FEEDBACK_FAILURE:null,
	
	SUPPLEMENT_ANSWER_SUCCESS:null,
	SUPPLEMENT_ANSWER_FAILURE:null,

});